services:
  # Laravel 开发环境
  app:
    image: ghcr.io/dongasai/php-version-manager-mirror:latest
    container_name: pvm-mirror-laravel-dev
    restart: unless-stopped
    ports:
      - "34003:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:5XHjti/LRjG5IEFFoe3qx/5RJb8aX4lb0YuD+cdPgXg=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
