version: '3.8'

services:
  # Laravel 生产环境
  app:
    image: ghcr.io/dongasai/php-version-manager-mirror:latest
    container_name: pvm-mirror-laravel-prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - mirror_data:/var/www/html/data
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - pvm-mirror-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: pvm-mirror-laravel-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pvm-mirror-prod
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL 数据库 (可选)
  mysql:
    image: mysql:8.0
    container_name: pvm-mirror-laravel-mysql-prod
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pvm_mirror
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_USER: pvm_mirror
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pvm-mirror-prod
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  mirror_data:
    driver: local

networks:
  pvm-mirror-prod:
    driver: bridge
