version: '3.8'

services:
  # Laravel 应用
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pvm-mirror-laravel-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    depends_on:
      - redis
    networks:
      - pvm-mirror-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: pvm-mirror-laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pvm-mirror-network

  # MySQL 数据库 (可选)
  mysql:
    image: mysql:8.0
    container_name: pvm-mirror-laravel-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pvm_mirror
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: pvm_mirror
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pvm-mirror-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  pvm-mirror-network:
    driver: bridge
