name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, curl, json, zip

    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Create release archive
      run: |
        # 创建发布目录
        mkdir -p release/php-version-manager-mirror
        
        # 复制必要文件
        cp -r src release/php-version-manager-mirror/
        cp -r config release/php-version-manager-mirror/
        cp -r docker release/php-version-manager-mirror/
        cp -r bin release/php-version-manager-mirror/
        cp -r public release/php-version-manager-mirror/
        cp -r vendor release/php-version-manager-mirror/
        cp composer.json release/php-version-manager-mirror/
        cp README.md release/php-version-manager-mirror/
        cp LICENSE release/php-version-manager-mirror/
        cp CHANGELOG.md release/php-version-manager-mirror/
        
        # 创建数据目录
        mkdir -p release/php-version-manager-mirror/{data,logs,cache}
        touch release/php-version-manager-mirror/data/.gitkeep
        touch release/php-version-manager-mirror/logs/.gitkeep
        touch release/php-version-manager-mirror/cache/.gitkeep
        
        # 设置执行权限
        chmod +x release/php-version-manager-mirror/bin/pvm-mirror
        
        # 创建压缩包
        cd release
        tar -czf php-version-manager-mirror-${GITHUB_REF#refs/tags/}.tar.gz php-version-manager-mirror/
        zip -r php-version-manager-mirror-${GITHUB_REF#refs/tags/}.zip php-version-manager-mirror/

    - name: Generate changelog
      id: changelog
      run: |
        # 提取当前版本的更新日志
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        
        # 从CHANGELOG.md提取当前版本的更新内容
        if [ -f CHANGELOG.md ]; then
          # 简单的更新日志提取（可以根据需要改进）
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "## $VERSION" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "详细更新内容请查看 [CHANGELOG.md](CHANGELOG.md)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "CHANGELOG=Release $VERSION" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.changelog.outputs.VERSION }}
        body: ${{ steps.changelog.outputs.CHANGELOG }}
        files: |
          release/php-version-manager-mirror-${{ steps.changelog.outputs.VERSION }}.tar.gz
          release/php-version-manager-mirror-${{ steps.changelog.outputs.VERSION }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Docker latest tag
      run: |
        echo "Docker image will be automatically tagged as latest by the docker workflow"
